### ISSUE TITLE
[Feature Request] JEI support

### ISSUE THREAD

**Issue by medsal15** [NotSoEpic/deepdrilling#2]
Add JEI support to see the different items drilled from nodes.

**Comment by NotSoEpic** [comment]
It _is_ something I do want to do

The problem is that they use loot tables so the chance and item count has the potential to get very complex to convey (yet alone compute), not to mention quality and other conditional stuff
So it might just end up being a hack that only lists the potential items

If you're desperate to see exactly what ore nodes drop what right now you can look through [the loot table jsons](https://github.com/NotSoEpic/deepdrilling/tree/master/common/src/main/resources/data/deepdrilling/loot_tables/ore_nodes) or open the .jar file as a .zip and find the tables there

**Comment by Squawkykaka** [comment]
potential items would be good

**Comment by NotSoEpic** [comment]
Implemented with v1.1.0 🎉
