### ISSUE TITLE
Suggestion: Data-driven content for modpack makers

### ISSUE THREAD

**Issue by GermanArtur** [NotSoEpic/deepdrilling#6]
Data-driven Drill Heads and Ores to provide other mods compat

**Comment by NotSoEpic** [comment]
Drill Heads are hopefully coded in such a way that _mod devs_ can easily add new ones. "Data driven" adding new ones is not in the scope because that would require registering brand new blocks + block entities through a completely custom user-facing system

Ores on the other hand are [already data driven](https://github.com/NotSoEpic/deepdrilling/blob/master/common/src/main/resources/data/deepdrilling/ore_nodes/copper.json) - if you really need extra blocks KubeJS should more than suffice for creating unbreakable dummy blocks
